[
  "Buval",
  "Nen Henry 1st Edition",
  "Duvel",
  "Trappist Westvleteren 12",
  "Stella Artois",
  "Delirium Tremens",
  "Weizen",
  "Tank 7",
  "Orval",
  "Westmalle Trappist Dubbel",
  "Battelaar",
  "3 Fonteinen Zenne y Frontera (season 18|19) Blend No. 93",
  "Abricot 2021",
  "Tripel d'Anvers",
  "Filou",
  "OMER. Traditional Blond",
  "Delta IPA",
  "Klootzakske",
  "Gust",
  "Juice Junkie",
  "Jour De Fête",
  "BMX IPA",
  "Schoppeke IPA",
  "Hoptimist",
  "Pinard De Bruxelles (Vintage 2020)",
  "Blonden Os",
  "Troubadour Magma",
  "Vedett Extra Pilsner (Extra Blond)",
  "Pauwel Kwak",
  "Singha",
  "Gouden Carolus Whisky Infused",
  "Monte Cristo",
  "Duvel Tripel Hop Cashmere",
  "Aoltbeer (2021-07) Pinot Noir",
  "Hazy Discovery Vilnius",
  "Nova",
  "Fourchette",
  "Chasselas",
  "Oude Gueuze (2015)",
  "3 Fonteinen Pruim Mirabelle (season 20|21) Blend No. 11",
  "Nue (鵺)",
  "Einder",
  "Paljas Saison",
  "Den Tuymelaar Special Edition 2021",
  "Den Tuymelaar Blond",
  "Den Tuymelaar",
  "Cloet IPA",
  "Bière des Amis 0.0",
  "Oude Kriek (Vieille)",
  "Straffe Hendrik Brugs Tripel Bier 9°",
  "6th Libertus Cuvée",
  "Bersalis Tripel",
  "Maredsous Blonde / Blond",
  "Blonden Os",
  "CORNET Smoked",
  "Brugge Tripel",
  "Lutgarde Blanche",
  "Luvanium Wintertijd Old Genever",
  "Troubadour Magma Special Edition 2015 Tripel Spiked Brett",
  "Bruxellensis",
  "SchuppenBoer Winter Rum Barrel Aged 2021",
  "Duchesse Chocolate Cherry",
  "Libertus 900 Jubileum Bier",
  "Straffe Hendrik Brugs Tripel Bier Wild (2021)",
  "Chimay Cinq Cents (White)",
  "CORNET Oaked Alcohol-free",
  "Ignis Quadruple",
  "ART50 New England DIPA",
  "Duvel Barrel Aged (2021) - Batch 6 Jamaican Rum Edition",
  "Bersalis Tripel Oak Aged",
  "Paix Dieu",
  "NO PHANTASM NO CARE",
  "Zundert 8",
  "Chimay Grande Réserve (Blue) (2018)",
  "Barleywine (Porto Oak)",
  "Duvel",
  "Buval",
  "Maneblusser",
  "2nd Quirinus Groen",
  "Brugse Zot",
  "Cevada",
  "Duvel Tripel Hop Citra",
  "Duvel 6,66%",
  "Kasteel Nitro Rouge",
  "Pauwel Kwak",
  "Geuze Mariage Parfait (2017)",
  "Steenbrugge Blond",
  "Rodenbach FruitAge",
  "Duchesse de Bourgogne",
  "Lupulus Hibernatus",
  "Staffstuff 2021",
  "Now or Never",
  "Leffe Bière d'Hiver / Winterbier",
  "Astrum Pale Ale",
  "Stella Artois",
  "Buval",
  "Mythos",
  "Duvel",
  "Trappist Westvleteren 12",
  "Duvel Tripel Hop Citra",
  "Sybil",
  "Orval",
  "Riesling Ivy",
  "Bavik Super Pils",
  "Kwaremont",
  "Maneblusser",
  "Gust",
  "Tripel d'Anvers",
  "Westmalle Trappist Tripel",
  "Pinard De Bruxelles (Vintage 2020)",
  "Kerel IPA",
  "All Day Vacay",
  "New Day Session IPA",
  "Ipanema",
  "WILD13 Bière De Soif Refermented With Red Regent And Rondo Grapes Blend 2021",
  "Fourchette (2021)",
  "Hoot & Aboot",
  "Chasselas",
  "Curieuse Neus",
  "3 Fonteinen Zenne y Frontera (season 18|19) Blend No. 93",
  "Pinot Noir Lambic - DANSAERT",
  "Nue (鵺)",
  "Einder",
  "Coulis - Vild",
  "Cider Lambic (2021) - DANSAERT",
  "The Way It Could Have Been",
  "Abricot 2021",
  "Barrel Aged",
  "Jupiler Red Inside",
  "Grimbergen Blonde",
  "Tripel Karmeliet",
  "St. Hubertus Triple Blond",
  "La Trappe Blond",
  "Nastro Azzurro",
  "Helse Engel",
  "Blanche de Liège",
  "Tank 7",
  "Surréaliste",
  "Dodgeball",
  "Duvel",
  "Duvel 6,66%",
  "Duvel Tripel Hop Citra",
  "Gouden Carolus Tripel",
  "Wipers Times Blond",
  "Duvel Tripel Hop Cashmere",
  "Ouwen Duiker",
  "Keekebisj Bio",
  "Trappist Westvleteren 12",
  "Gouden Carolus Whisky Infused",
  "Warmouth v7",
  "Duvel Barrel Aged (2022) - Batch 7 Irish Whiskey Edition",
  "Gouden Carolus Indulgence 2022 - Festiva",
  "Gouden Carolus Ambrio",
  "Gouden Carolus Cuvée van de Keizer Imperial Dark (2018)",
  "Delirium Blond Barrel Aged",
  "Party On A Jamaican Beach",
  "Gouden Carolus Cuvée van de Keizer Imperial Dark (2022)",
  "Super Juice",
  "Kerel Saison",
  "Airborne Bière Tripel Blonde",
  "Tripel d'Anvers",
  "Tropical IPA Mokke ",
  "CORNET Oaked",
  "Simpel Duif",
  "Gouden Carolus Hopsinjoor",
  "Kwaremont",
  "Den Ouden Burgemeester",
  "Tank 7",
  "Common Circuits",
  "Gouden Carolus Indulgence 2022 - Cuvée Sauvage",
  "Tipsy Gold",
  "Trappistes Rochefort 6",
  "Duvel Barrel Aged (2022) - Batch 7 Irish Whiskey Edition",
  "Gulden Draak Classic",
  "Bootjes Bier",
  "Vaccin 1.0",
  "Barbãr",
  "Babylone",
  "Airborne Bière Tripel Blonde",
  "Airborne Bière Blonde",
  "Wipers Times Blond",
  "La Chouffe Blond",
  "Chouffe Soleil",
  "Trappistes Rochefort 8",
  "La Trappe Tripel",
  "Kompel Pils",
  "Corsendonk Agnus Tripel / Abbey Pale Ale",
  "Duckstein Rotblond Original",
  "Gouden Carolus Tripel",
  "Gouden Carolus Christmas / Noël",
  "Gaffels Sonnen Hopfen",
  "Klootzakske",
  "Trappist Westvleteren 12",
  "Abt 12",
  "Buval",
  "Jungle Joy",
  "Chérie Bière Blanche à la Framboise",
  "Kasteel Rouge",
  "Hoegaarden Rosée",
  "Litchi Cider",
  "Guinness Draught",
  "Nen Henry 1st Edition",
  "Duchesse de Bourgogne",
  "Red Fruit",
  "Cara Rouge",
  "Cara Blond",
  "Salitos Tequila",
  "Buval",
  "Salitos Tequila",
  "Den Tuymelaar Special Edition 2021",
  "Den Tuymelaar Blond",
  "Den Tuymelaar",
  "Saison d'Erpe-Mere",
  "Nørd Bliss",
  "Taras Boulba",
  "Orval",
  "Delirium Tremens",
  "Hoegaarden Wit / Blanche",
  "Tripel Karmeliet",
  "Tank 7",
  "Duvel",
  "Papegaei",
  "Staropramen Dark / Černý ležák",
  "Staropramen Granát",
  "Bière des Amis 0.0",
  "Tripel Karmeliet",
  "CORNET Oaked",
  "Hirter Radler Kräuter",
  "Zillertal Gauder Steinbock Reserve - Barrique",
  "Boer Bloem",
  "Somersby Blackberry",
  "Strongbow Red Berries",
];
